### PR TITLE
Missing vega functions

### PR DESCRIPTION
**Pull request by martinRenou**
- [x] type checking functions
- [x] type coercing functions
- [x] date time functions
- [x] array functions
- [x] string functions
- [x] object functions
- [x] formatting functions
- [x] regexp functions
- [x] color functions
- [x] scale functions

### CODE REVIEW

**Comment by maartenbreddels** [comment]
can these python 'placeholder' functions be generated from a spec?

**Comment by martinRenou** [comment]
Yes I had it in mind, did not find a spec though

**Comment by maartenbreddels** [comment]
It seems https://github.com/vega/vega/blob/master/docs/docs/expressions.md is manually written and includes HTML, so it doesn't seem like an easy route.

**Comment by martinRenou** [comment]
True.. Maybe we could open an issue in vega-expressions

**Comment by maartenbreddels** [comment]
Indeed, since I have no idea where they are coming from, could you open an issue an ping me?

**Comment by martinRenou** [comment]
Sure :)

**Pull request merged**
